/* eslint-disable @next/next/no-img-element */
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Button from "../../components/Button";
import CardEvent from "../../components/CardEvent";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import Statistic from "../../components/Statistic";
import Story from "../../components/Story";
import { useRouter } from "next/router";
import { getData } from "../../utils/fetchData";
import moment from "moment";
import { formatDate } from "../../utils/formatDate";

const Detail = ({ data }) => {
  const router = useRouter();

  const [dataLandingPage, setDataLandingPage] = useState([]);

  const fetchData = async () => {
    try {
      const response = await getData("api/v1/participant/landing-page");

      setDataLandingPage(response.data?.data);
    } catch (error) {
      console.log(error?.response?.data);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleSubmit = () => {
    router.push("/checkout");
  };

  return (
    <>
      <Head>
        <title>Semina || Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <div className="preview-image bg-navy text-center">
        <img
          src="/images/details-image.png"
          className="img-content"
          alt="semina"
        />
      </div>
      <div className="details-content container">
        <div className="d-flex flex-wrap justify-content-lg-center gap">
          <div className="d-flex flex-column description">
            <div className="headline">{data.tagline}</div>
            <div className="event-details">
              <h6>Event Details</h6>
              <p className="details-paragraph">{data.about}</p>
            </div>
            <div className="keypoints">
              {data.keyPoint.map((key, i) => {
                return (
                  <div className="d-flex align-items-start gap-3" key={i}>
                    <img src="/icons/ic-check.svg" alt="semina" />
                    <span>{key}</span>
                  </div>
                );
              })}
            </div>
            <div className="map-location">
              <h6>Event Location</h6>
              <div className="map-placeholder">
                <div className="maps">
                  <img src="/images/maps.png" alt="" />
                  <div
                    className="absolute d-flex justify-content-center align-items-center"
                    id="hoverMe"
                  >
                    <a href="#" className="btn-navy" id="btn-maps">
                      View in Google Maps
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="d-flex flex-column card-event">
            <h6>Your Speaker</h6>
            <div className="d-flex align-items-center gap-3 mt-3">
              <img
                src={
                  data?.speaker?.avatar !== "images/avatar.png"
                    ? `${process.env.NEXT_PUBLIC_API_IMAGE}/speaker/${data?.speaker?.avatar}`
                    : `${process.env.NEXT_PUBLIC_API}/${data?.speaker?.avatar}`
                }
                alt="semina"
                width="60"
              />
              <div>
                <div className="speaker-name">{data?.speaker?.name}</div>
                <span className="occupation">{data?.speaker?.role}</span>
              </div>
            </div>
            <hr />

            <h6>Get Ticket</h6>
            <div className="price my-3">
              {data.price === 0 ? "free" : `$${data.price}`}
              <span>/person</span>
            </div>
            <div className="d-flex gap-3 align-items-center card-details">
              <img src="/icons/ic-marker.svg" alt="semina" /> {data.venueName}
            </div>
            <div className="d-flex gap-3 align-items-center card-details">
              <img src="/icons/ic-time.svg" alt="semina" />{" "}
              {moment(data.date).format("HH.MM A")}
            </div>
            <div className="d-flex gap-3 align-items-center card-details">
              <img src="/icons/ic-calendar.svg" alt="semina" />{" "}
              {formatDate(data.date)}
            </div>

            {data.stock !== 0 && (
              <Button variant={"btn-green"} action={handleSubmit}>
                Join Now
              </Button>
            )}
          </div>
        </div>
      </div>

      <CardEvent
        data={dataLandingPage}
        title="Similiar Events"
        subTitle="Next One"
      />
      <Story />
      <Statistic />
      <Footer />
    </>
  );
};

export default Detail;

export async function getServerSideProps({ params }) {
  const response = await getData(`api/v1/participant/detail-page/${params.id}`);
  const data = response.data?.data;

  return {
    props: {
      data,
    },
  };
}
