import React from "react";
import Head from "next/head";
import Header from "../components/Header";

const Browse = () => {
  return (
    <>
      <Head>
        <title>Semina || Browse Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  );
};

export default Browse;
