import React from "react";
import Head from "next/head";
import Brand from "../components/Brand";
import FormSignIn from "../components/FormSignIn";
import Navbar from "../components/Navbar";

const SignIn = () => {
  return (
    <>
      <Head>
        <title>Semina || Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>
      <section className="login header bg-navy">
        <div className="container">
          <div className="d-flex flex-column align-items-center hero gap-5">
            <div>
              <div className="hero-headline text-start">Sign In</div>
            </div>
            <FormSignIn />
          </div>
        </div>
      </section>
      <Brand className="pt-0 bg-navy" />
    </>
  );
};

export default SignIn;

export async function getServerSideProps({ req }) {
  const { token } = req.cookies;

  if (token) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
